branches:
  only:
    - master
    - develop
    - /^feature/poc/.*$/

language: java
jdk: openjdk11

services:
  - docker

stages:
  - build
  - publish

jobs:
  include:
    - stage: build
      addons:
        sonarcloud:
          organization: "algalopez"
          token: ${SONARCLOUD_TOKEN}
      script:
        - ./gradlew buildDatabaseDocker
        - ./gradlew runDatabaseDocker
        - ./gradlew createDb
        - ./gradlew clean build
        - ./gradlew jacocoTestReport
        - ./gradlew sonarqube
        - ./gradlew copyArtifacts
        - ./gradlew zipArtifacts
    - stage: publish
      branches:
        only:
          - master
          - develop
      script:
        - ./gradlew buildDatabaseDocker
        - ./gradlew buildAppDocker
        - ./gradlew loginToRegistry
        - ./gradlew createDatabaseTag
        - ./gradlew createAppTag
        - ./gradlew publishDatabaseImage
        - ./gradlew publishAppImage
        - ./gradlew logoutFromRegistry
