branches:
  only:
    - master
    - develop
    - /^feature/poc/.*$/

install: gradle wrapper --gradle-version 5.6.3

language: java
jdk: openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "algalopez"
    token:
      secure: "57d6c1d150401a65393afae7dcd817ff35c703fb"

script:
  - ./gradlew buildDatabaseDocker
  - ./gradlew runDatabaseDocker
  - ./gradlew createDatabase
  - ./gradlew clean build
  - ./gradlew sonarqube
  - ./gradlew copyArtifacts
  - ./gradlew zipArtifacts
