branches:
  only:
    - master
    - develop
    - /^feature/poc/.*$/

language: java
jdk: openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "algalopez"
    token:
      secure: $SONARCLOUD_TOKEN

stages:
  - build
  - publish

jobs:
  include:
    - stage: build
      script:
        - ./gradlew buildDatabaseDocker
        - ./gradlew runDatabaseDocker
        - ./gradlew createDb
        - ./gradlew clean build
        - ./gradlew sonarqube -Dsonar.login=$SONARCLOUD_TOKEN
        - ./gradlew copyArtifacts
        - ./gradlew zipArtifacts
    - stage: publish
      branches:
        only:
          - master
          - develop
      script:
        - ./gradlew buildDatabaseDocker
        - ./gradlew buildAppDocker
        - ./gradlew loginToRegistry
        - ./gradlew createDatabaseTag
        - ./gradlew createAppTag
        - ./gradlew publishDatabaseImage
        - ./gradlew publishAppImage
        - ./gradlew logoutFromRegistry
