branches:
  only:
    - master
    - develop
    - /^feature/poc/.*$/

language: java
jdk: openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "algalopez"
    token:
      secure: $SONARCLOUD_TOKEN

script:
  - ./gradlew buildDatabaseDocker
  - ./gradlew runDatabaseDocker
  - ./gradlew createDb
  - ./gradlew clean build
  - ./gradlew sonarqube
  - ./gradlew copyArtifacts
  - ./gradlew zipArtifacts
