version: "3"
services:
  grafana:
    image: grafana/grafana:6.6.2
    ports:
      - "3000:3000"
    networks:
      - network_grafana
    links:
      - graphite
  graphite:
    tty: true
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - network_grafana
networks:
  network_grafana:
    driver: bridge
