name: Tunturi CICD Pipeline
on:
    push:
        branches:
            -   master
            -   develop
            -   'pipeline/**'
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Java version
                uses: actions/setup-java@v1
                with:
                    java-version: '11.0.7'
                    java-package: jdk
                    architecture: x64
            -   name: Build and unit tests
                run: |
                    PROJECT_VERSION=`cat gradle.properties | grep "project_version" | cut -d'=' -f2`
                    echo $PROJECT_VERSION
                    chmod +x gradlew
                    ./gradlew buildDatabaseDocker
                    ./gradlew runDatabaseDocker
                    ./gradlew createDb
                    ./gradlew clean build
                    ./gradlew copyArtifacts
                    ./gradlew zipArtifacts

            -   name: Quality gate
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
                run: |
                    ./gradlew jacocoTestReport
                    ./gradlew sonarqube -Dsonar.organization=algalopez -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
            -   name: Upload artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: artifacts
                    path: 'artifact/bin/'
    publish:
        name: Push to registry
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Download artifacts
                uses: actions/download-artifact@v1
                with:
                    name: artifacts
                    path: 'artifact/bin/'
            -   name: Build images and create atgs
                run: |
                    ls -la artifact/bin
                    ./gradlew buildDatabaseDocker
                    ./gradlew buildAppDocker
                    ./gradlew createDatabaseTag
                    ./gradlew createAppTag
            -   name: Publish to DockerHub registry
                env:
                    DOCKERHUB_REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
                run: |
                    ./gradlew loginToRegistry
                    ./gradlew publishDatabaseImage
                    ./gradlew publishAppImage
                    ./gradlew logoutFromRegistry
            -   name: Publish to GitHub registry
                run: |
                    PROJECT_VERSION=`cat gradle.properties | grep "project_version" | cut -d'=' -f2`
                    docker login docker.pkg.github.com --username ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
                    docker push docker.pkg.github.com/algalopez/tunturi/tunturi-db:PROJECT_VERSION
                    docker push docker.pkg.github.com/algalopez/tunturi/tunturi-app:PROJECT_VERSION
                    docker logout docker.pkg.github.com

#login: docker login docker.pkg.github.com --username algalopez -p <TOKEN>
#login: docker login --username algalopez -p <TOKEN>
#logout: docker logout docker.pkg.github.com
#logout: docker logout
#dbTag: docker tag db-docker docker.pkg.github.com/algalopez/tunturi/tunturi-db-docker:<PROJECT_VERSION>
#dbTag: docker tag db-docker algalopez/tunturi-db:<PROJECT_VERSION>
#appTag: docker tag app-docker docker.pkg.github.com/algalopez/tunturi/tunturi-app-docker:<PROJECT_VERSION>
#appTag: docker tag app-docker algalopez/tunturi-app:<PROJECT_VERSION>
#bdPublish: docker push docker.pkg.github.com/algalopez/tunturi/tunturi-db-docker:<PROJECT_VERSION>
#bdPublish: docker push algalopez/tunturi-db:<PROJECT_VERSION>
#appPublish: docker push docker.pkg.github.com/algalopez/tunturi/tunturi-app-docker:<PROJECT_VERSION>